website/views.py
'''Arquivo para as outras funções'''
from datetime import datetime
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import Usuario, Materia, Topico, Anotacao
from . import db
from flask_login import login_required, current_user

views = Blueprint('views', __name__)

@login_required
@views.route('/logado')
def logado():
    materias = Materia.query.filter(Materia.id_usuario==current_user.id).all()
    return render_template('logado.html', materias=materias)

@login_required
@views.route('/adicionar_materia', methods=['POST'])
def adicionar_materia():
    nome = request.form['nome']
    if nome == '':
        flash('A matéria precisa ter um nome.', category='error')
        return redirect(url_for('views.logado'))
    materia = Materia(nome=nome, id_usuario=current_user.id)
    db.session.add(materia)
    db.session.commit()
    flash('Matéria adicionada com sucesso!', 'success')
    return redirect(url_for('views.logado'))

@login_required
@views.route('/materia/<int:id_materia>')
def materia(id_materia):
    materia = Materia.query.get(id_materia)
    return render_template('materia.html', materia=materia)

@login_required
@views.route('/topico/<int:id_topico>')
def topico(id_topico):
    topico = Topico.query.get(id_topico)
    # Calcula a diferença de dias entre o prazo e a data de criação
    diferenca = None  # Inicialmente definimos a diferença como None
    if topico.prazo:
        hoje = datetime.utcnow().date()
        prazo = datetime.strptime(topico.prazo, '%Y-%m-%d').date()
        diferenca = (prazo - hoje).days
    return render_template('topico.html', topico=topico, diferenca=diferenca)

@login_required
@views.route('/adicionar_topico/<int:id_materia>', methods=['POST'])
def adicionar_topico(id_materia):
    nome = request.form['nome']
    prazo_str = request.form['prazo']
    if nome == '':
        flash('O tópico precisa ter um nome.', category='error')
        return redirect(url_for('views.materia', id_materia=id_materia))
    topico = Topico(nome=nome, id_materia=id_materia, prazo=prazo_str)
    db.session.add(topico)
    db.session.commit()

    flash('Tópico e prazo adicionados com sucesso!', 'success')
    return redirect(url_for('views.materia', id_materia=id_materia))

@login_required
@views.route('/marcar_completo/<int:id_topico>/<int:finalizado>', methods=['POST','GET'])
def marcar_completo(id_topico, finalizado):
    topico = Topico.query.get(id_topico)
    if finalizado == 1:
        topico.completo = True
        flash('Tópico marcado como concluído!', 'success')
    else:
        topico.completo = False
        flash('Tópico marcado como não concluído!', 'danger')
    db.session.commit()
    return redirect(url_for('views.topico', id_topico=topico.id))

@login_required
@views.route('/adicionar_anotacao/<int:id_topico>', methods=['POST'])
def adicionar_anotacao(id_topico):
    texto = request.form['texto']
    if texto == '':
        flash('A anotação não pode estar vazia.', category='error')
        return redirect(url_for('views.topico', id_topico=id_topico))
    anotacao = Anotacao(texto=texto, id_topico=id_topico)
    db.session.add(anotacao)
    db.session.commit()
    flash('Anotação adicionada com sucesso!', 'success')
    return redirect(url_for('views.topico', id_topico=id_topico))

@login_required
@views.route('/excluir_topico/<int:id_topico>', methods=['POST'])
def excluir_topico(id_topico):
    topico = Topico.query.get(id_topico)
    
    if topico:
        # Exclua o tópico do banco de dados
        db.session.delete(topico)
        db.session.commit()
        flash('Tópico excluído com sucesso!', 'success')
    else:
        flash('Tópico não encontrado', 'danger')
    
    # Redirecione de volta para a página de detalhes da matéria
    return redirect(url_for('views.materia', id_materia=topico.id_materia))

@login_required
@views.route('/excluir_anotacao/<int:id_anotacao>', methods=['POST'])
def excluir_anotacao(id_anotacao):
    anotacao = Anotacao.query.get(id_anotacao)
    
    if anotacao:
        # Exclua o tópico do banco de dados
        db.session.delete(anotacao)
        db.session.commit()
        flash('Anotação excluída com sucesso!', 'success')
    else:
        flash('Anotação não encontrada', 'danger')
    
    # Redirecione de volta para a página de detalhes da matéria
    return redirect(url_for('views.topico', id_topico=anotacao.id_topico))

@login_required
@views.route('/excluir_materia/<int:id_materia>', methods=['POST'])
def excluir_materia(id_materia):
    materia = Materia.query.get(id_materia)
    
    if materia:
        # Exclua o tópico do banco de dados
        db.session.delete(materia)
        db.session.commit()
        flash('Matéria excluída com sucesso!', 'success')
    else:
        flash('Matéria não encontrada', 'danger')
    
    # Redirecione de volta para a página de detalhes da matéria
    return redirect(url_for('views.logado'))

website/templates/cadastro.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='cadastro.css') }}">
    <title>Gerenciador de Tarefas</title>
</head>
<body>
    <header>
        <h1> Gerenciador de Tarefas</h1>
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <section class="arealogin">
        <div class="login">
            <h2>Cadastro</h2>
            <form method="post">
                <br>
                <input type="text" name="usuario" placeholder="Digite seu usuário">
                <br>
                <input type="text" name="nome" placeholder="Digite seu nome">
                <br>
                <input type="password" name="senha1" placeholder="Digite sua senha">
                <input type="password" name="senha2" placeholder="Confirme sua senha">
                <br>
                <br>
                <button type="submit" value="login">Cadastrar</button>
                <p> Já possui um cadastro? <a href="/">Entre aqui</a></p>
            </form>
        </div>
    </section>

</body>
</html>

website/templates/logado.html
<!DOCTYPE html>
<html>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='logado.css') }}">
<head>
    <title>Página Logada</title>
</head>
<body>
    <header>
        <h1>Gerenciador de Tarefas</h1>
        <a href="/logout" class="logout">Deslogar</a>
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <section class="arealogin">
        <div class="login">
    <h2>Bem-vindo, {{ current_user.nome }}!</h2>
    <br>
    <br>
    <br>
    <a>Suas Matérias:</a>
    <ul>
        {% for materia in materias %}
            <li class="materias-button">
                <form method="GET" action="{{ url_for('views.materia', id_materia=materia.id) }}">
                    <input type="hidden" name="materia_id" value="{{ materia.id }}">
                    <button class="btnmateria" type="submit" class="btn btn-info">{{ materia.nome }}</button>
                </form>
                <form method="POST" action="{{ url_for('views.excluir_materia', id_materia=materia.id) }}">
                    <button type="submit" class="btnexcluir">X</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    <br>
    <a>Adicionar Matéria:</a>
    <form method="POST" action="{{ url_for('views.adicionar_materia') }}">
        <input type="text" name="nome" placeholder="Nome da matéria" class="inputmateria">
        <input type="submit" value="Adicionar" class="btnadicionar">
    </form>
        </div>
        <div class="fill">
    </section>
</body>
</html>

website/templates/login.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='login.css') }}">
    <title>Gerenciador de Tarefas</title>
</head>

<body>
    <header>
        <h1> Gerenciador de Tarefas</h1>
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <section class="arealogin">
        <div class="login">
            <h2>Login</h2>
            <form method="post">
                <br>
                <input type="text" name="usuario" placeholder="Usuário">
                <input type="password" name="senha" placeholder="Senha">
                <br>
                <br>
                <button type="submit" value="login">Entrar</button>
                <p> Não possui um cadastro? <a href="cadastro">Cadastre-se aqui</a></p>
            </form>
        </div>
    </section>

    

</body>
</html>

website/templates/materia.html
<!DOCTYPE html>
<html>
<head>
    <title>Detalhes da Matéria</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='materia.css') }}">
</head>
<body>
    <header>
        <h1>Gerenciador de Tarefas</h1>
    <a href="/logado" class="voltar">Voltar</a>
    <a href="/logout" class="logout">Deslogar</a>
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <section class="arealogin">
    <div class="login">
    <h2>{{ materia.nome }}</h2>
    <br>
    <br>
    <a>Tópicos:</a>
    <ul>
        {% for topico in materia.topicos %}
            <li class="topic-button">
                <form method="GET" action="{{ url_for('views.topico', id_topico=topico.id) }}">
                    <input type="hidden" name="topico_id" value="{{ topico.id }}">
                    {% if topico.completo %}
                        <button type="submit" class="btntopico"><del>{{ topico.nome }}</del></button>
                    {% else %}
                    <button type="submit" class="btntopico">{{ topico.nome }}</button>
                    {% endif %}
                </form>
                <form method="POST" action="{{ url_for('views.excluir_topico', id_topico=topico.id) }}">
                    <button type="submit" class="btnexcluir">X</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    <br>
    <br>
    <form method="POST" action="{{ url_for('views.adicionar_topico', id_materia=materia.id) }}">
        <a>Adicionar tópico:</a>
        <input type="text" name="nome" class="inputtopico" placeholder="Nome do tópico">
        <input type="date" id="prazo" name="prazo" class="inputprazo" placeholder="Prazo para o tópico">
        <input type="submit" value="Adicionar" class="btnadicionar">
    </form>
    </div>
    </section>
</body>
</html>

website/templates/topico.html
<!DOCTYPE html>
<html>
<head>
    <title>Detalhes do Tópico</title>
    <!DOCTYPE html>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='topico.css') }}">
    <html>
    <head>
        <title>Detalhes do Tópico</title>
</head>
<body>
    <header>
        <h1>Gerenciador de Tarefas</h1> 
        <a href="/materia/{{topico.id_materia}}" class="voltar">Voltar</a>
        <a href="/logout" class="logout">Deslogar</a>
        {% if topico.completo %}
            <a href="/marcar_completo/{{topico.id}}/0" class="completo">Tópico não concluído</a>   
        {% else %}
        <a href="/marcar_completo/{{topico.id}}/1" class="completo">Tópico concluído</a>
        {% endif %}
    </header>
    {% with messages = get_flashed_messages(with_categories=true) %} 
    {% if messages %} 
    {% for category, message in messages %} 
    {% if category == 'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    <section class="arealogin">
    <div class="login">
    <h2>{{ topico.nome }}</h2>
    {% if topico.completo %}
        <p>Tópico concluído!</p>
    {% else %}
        {% if topico.prazo %}
            {% if diferenca >= 0 %}
                <p>Faltam {{ diferenca }} dias para o prazo do tópico.</p>
            {% else %}
                <p>O tópico está {{ -1*diferenca }} dias atrasado.</p>
            {% endif %}
        {% else %}
            <p>O prazo não foi definido.</p>
        {% endif %}
    {% endif %}
    <br>
    <br>
    <a>Anotações:</a>
    <br>
    <br>
    <ul>
        {% for anotacao in topico.anotacoes %}
            <li class="anotacoes">
                <form method="GET" action="{{ url_for('views.topico', id_topico=topico.id) }}">
                    <li><a class="anotacao">{{ anotacao.texto }}</a></li>
                </form>
                <form method="POST" action="{{ url_for('views.excluir_anotacao', id_anotacao=anotacao.id) }}">
                    <button type="submit" class="btnexcluir">X</button>
                </form>
            </li>
        {% endfor %}
    </ul>
    <br>
    <a>Adicionar Anotação:</a>
    <form method="POST" action="{{ url_for('views.adicionar_anotacao', id_topico=topico.id) }}">
        <textarea name="texto" placeholder="Escreva sua anotação aqui" class="textarea1" rows="6" cols="30"></textarea>
        <input type="submit" value="Adicionar" class="btnadicionar">
    </form>
</body>
</html>